name: Debug

on:
  workflow_dispatch:
  push:

jobs:
  not_working:
    runs-on: ubuntu-latest
    container:
      # Use 'bookworm' (Debian 12), which has GLIBC 2.38 preinstalled
      image: python:3.10-bookworm
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python
