name: Debug

on:
  workflow_dispatch:
  push:

jobs:
  not_working:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y wget curl ca-certificates

      - name: Install Precompiled glibc 2.38
        run: |
          wget -q -O /tmp/glibc-2.38.tar.gz https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.38-r0/glibc-2.38-r0.apk
          tar -xvzf /tmp/glibc-2.38.tar.gz -C /opt
          echo "/opt/glibc-2.38/lib" > /etc/ld.so.conf.d/glibc-2.38.conf
          ldconfig
          export LD_LIBRARY_PATH=/opt/glibc-2.38/lib:$LD_LIBRARY_PATH

      - name: Verify glibc version
        run: ldd --version

      - name: Run Python
        run: python --version
