name: Debug

on:
  workflow_dispatch:
  push:

jobs:
  not_working:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
          build-essential manpages-dev gawk bison wget curl \
          binutils gcc libc-dev make python3-dev

      - name: Download and Compile glibc 2.38
        run: |
          wget http://ftp.gnu.org/gnu/libc/glibc-2.38.tar.gz
          tar -xvzf glibc-2.38.tar.gz
          cd glibc-2.38
          mkdir build
          cd build
          ../configure --prefix=/opt/glibc-2.38
          make -j$(nproc)
          make install

      - name: Update glibc Paths
        run: |
          echo "/opt/glibc-2.38/lib" > /etc/ld.so.conf.d/glibc-2.38.conf
          export LD_LIBRARY_PATH=/opt/glibc-2.38/lib:$LD_LIBRARY_PATH
          ldconfig

      - name: Verify glibc Version
        run: ldd --version

      - name: Run Python
        run: python --version
