name: Debug

on:
  workflow_dispatch:
  push:

jobs:
  not_working:
    runs-on: ubuntu-latest
    container:
      # Use 'bookworm' (Debian 12), which has GLIBC 2.38 preinstalled
      image: python:3.10-bookworm
    steps:
      - name: Verify GLIBC Version
        run: ldd --version

      - name: Run Python
        run: python --version
