name: Debug

on:
  workflow_dispatch:
  push:
  
jobs:
  not_working:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y wget build-essential gawk bison make

          # Download and build glibc 2.38
          wget http://ftp.gnu.org/gnu/libc/glibc-2.38.tar.gz
          tar -xvzf glibc-2.38.tar.gz
          cd glibc-2.38
          mkdir build && cd build
          ../configure --prefix=/opt/glibc-2.38
          make -j$(nproc)
          make install

          # Update LD_LIBRARY_PATH to include new glibc
          echo "/opt/glibc-2.38/lib" > /etc/ld.so.conf.d/glibc-2.38.conf
          ldconfig
          export LD_LIBRARY_PATH=/opt/glibc-2.38/lib:$LD_LIBRARY_PATH

      - name: Verify glibc version
        run: |
          ldd --version

      - name: Run Python
        run: |
          python --version
