name: Debug

on:
  workflow_dispatch:
  push:

jobs:
  not_working:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - name: Verify Python Version
        run: python --version

      - name: Run Python Commands
        run: |
          python -c "print('Hello, GLIBC 2.38!')"
